  jf-splitter:
    build:
      context: ./jf-splitter
      dockerfile: Dockerfile
    container_name: jf-splitter
    image: jf-splitter
    restart: unless-stopped
    environment:
      - JF_UPSTREAM_A=http://jellyfinA:8096             # Jellyfin on same host like jf-splitter including same docker network
      - JF_UPSTREAM_B=http://jellyfinB:8096             # Jellyfin from another host, if not in the same network use wireguard
      - JF_TOKEN_A=${JF_TOKEN_A}
      - JF_TOKEN_B=${JF_TOKEN_B}